### ISSUE TITLE
Comments on functions.py

### ISSUE THREAD

**Issue by rahulporuri** [parththaker/OptimizationGeneric#1]
- [ ] pep8 suggests two lines between the import statement and the class declaration
- [ ] unless you're working with python3 only, it's always better to make the class inherit from `object`
- [ ] why is the class named `regression_function`?
- [ ] the `__init__` function (or any function for that matter) shouldn't be passed mutable arguments, in this case `features` and `labels`.
- [ ] pep8 also suggests limiting the line length to <80. but this is a very contentious issue so you can ignore this.
- [ ] what the `function_update` method is hard to understand, especially because of the long statement. it might be nice to create a private function that takes `self.labels[i]` and `self.features[i]`.
- [ ] you might consider using the `zip` function e.g. `for label, feature in zip(self.labels, self.featues)`

**Comment by parththaker** [comment]
Fixed in the previous commit. [Commit link](https://github.com/parththaker/OptimizationGeneric/commit/94d0851220a255c233d84087d953d5f4157ad600)
